Move version from const.py to __init__.py for Flit static introspection
praw-dev/prawcore pull request #165
Opened 2023-10-20 22:27 UTC by CAM-Gerlach

As discussed in #164 , moving `__version__` from `const.py` to be directly in `__init__,py` allows Flit to statically introspect it, preventing `requests` from being required as an unspecified, implict build-time dependency, causing build/install failures in certain scenarios. I've tested and confirmed locally that this fix allows successfully building and installing `prawcore` without having `requests` in the local environment.

Additionally, I've updated the one internal module using this value from `const.py` to use that from `__init__.py`. I did have to switch from a relative `from` import to an absolute import to avoid an import cycle error; alternatively, I could also move the import to be inside the relevant function, though I figured the former would be more acceptable/less problematic for you—happy to change that as desired.

Finally, I updated the version bump script in `tools/set_version.py` to bump the version in its new location.

2023-10-21 04:10 UTC, LilSpazJoekp requested changes
Yeah let's do a local import.

2023-10-21 04:10 UTC, LilSpazJoekp commented on prawcore/requestor.py
> +import prawcore
Let's do a local relative import.

2023-10-21 09:30 UTC, CAM-Gerlach commented on prawcore/requestor.py
> +import prawcore
Sure, done as requested :+1:

2023-10-21 14:00 UTC, LilSpazJoekp approved these changes

2023-10-21 14:00 UTC, merged

2023-10-21 14:01 UTC, LilSpazJoekp commented
Thanks for this!

Would you be interested in doing the same for PRAW, Async PRAW, and Asyncprawcore?

2023-12-15 22:20 UTC, CAM-Gerlach commented
Hey, sorry, was looking into this, but ran into a couple issues and then it fell through the cracks.

I opened praw-dev/praw#2004 to cover this in PRAW and discuss the implementation there; TL;DR we could do a similar approach, but it does require changing one other `const.py` module-level constant in a backward-incompatible way, so we may want to re-consider Approach 2 (static metadata) here, but that can be discussed over there.

As for `asyncpraw` and `asyncprawcore`, at the time I first looked into this request they were both still using Setuptools, but I see they are now using Flit, so they do indeed need this too, presumably. Asyncpraw runs into the same issue as PRAW with `USER_AGENT_FORMAT` and can be fixed the same way, with the same impact (albeit theoretical in this case); however, I note [one extant usage of `asyncpraw.const.__version__`](https://github.com/kaif-00z/TgRedditBot/blob/987a767d486976a4fe259a80484386a4165c9ed4/bot.py#L136) in the wild, in someone's Reddit bot with a handful of stars. Approach 2 (static metadata) would avoid this as well, as well as simplify the implementation there since it would essentially just require the same changes to `set_version.py` and `pyproject.toml` and that's it.